import 'package:hollow/hollow.dart';
import 'package:ui_kit/skeleton/condor_hollow_skeleton_ids.dart';

/// Call once before [runApp] so [Skeleton] widgets resolve shimmer geometry.
void registerCondorHollowBones() {
  HollowRegistry.register({
    CondorHollowSkeletonIds.coursesListMobile: const SkeletonResult(
      name: CondorHollowSkeletonIds.coursesListMobile,
      width: 1200,
      height: 500,
      bones: [
        // 6 list items (68px height, 14px spacing → 82px apart)
        Bone(
          x: 0,
          y: 0,
          w: 100,
          h: 68,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2.0,
          y: 9.0,
          w: 10.0,
          h: 50.0,
          borderRadius: BorderRadiusData.uniform(8),
        ),
        Bone(
          x: 0,
          y: 82,
          w: 100,
          h: 68,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2.0,
          y: 91.0,
          w: 10.0,
          h: 50.0,
          borderRadius: BorderRadiusData.uniform(8),
        ),
        Bone(
          x: 0,
          y: 164,
          w: 100,
          h: 68,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2.0,
          y: 173.0,
          w: 10.0,
          h: 50.0,
          borderRadius: BorderRadiusData.uniform(8),
        ),
        Bone(
          x: 0,
          y: 246,
          w: 100,
          h: 68,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2.0,
          y: 255.0,
          w: 10.0,
          h: 50.0,
          borderRadius: BorderRadiusData.uniform(8),
        ),
        Bone(
          x: 0,
          y: 328,
          w: 100,
          h: 68,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2.0,
          y: 337.0,
          w: 10.0,
          h: 50.0,
          borderRadius: BorderRadiusData.uniform(8),
        ),
        Bone(
          x: 0,
          y: 410,
          w: 100,
          h: 68,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2.0,
          y: 419.0,
          w: 10.0,
          h: 50.0,
          borderRadius: BorderRadiusData.uniform(8),
        ),
      ],
    ),
    CondorHollowSkeletonIds.lessonsListFullScreen: const SkeletonResult(
      name: CondorHollowSkeletonIds.lessonsListFullScreen,
      width: 360,
      height: 304,
      bones: [
        Bone(
          x: 0,
          y: 0,
          w: 100,
          h: 60,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2,
          y: 10,
          w: 10,
          h: 40,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: 15,
          y: 12,
          w: 50,
          h: 16,
          borderRadius: BorderRadiusData.uniform(4),
        ),
        Bone(
          x: 15,
          y: 34,
          w: 30,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),

        Bone(
          x: 0,
          y: 70,
          w: 100,
          h: 60,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2,
          y: 80,
          w: 10,
          h: 40,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: 15,
          y: 82,
          w: 55,
          h: 16,
          borderRadius: BorderRadiusData.uniform(4),
        ),
        Bone(
          x: 15,
          y: 104,
          w: 35,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),

        Bone(
          x: 0,
          y: 140,
          w: 100,
          h: 60,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2,
          y: 150,
          w: 10,
          h: 40,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: 15,
          y: 152,
          w: 45,
          h: 16,
          borderRadius: BorderRadiusData.uniform(4),
        ),
        Bone(
          x: 15,
          y: 174,
          w: 25,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),
      ],
    ),
    CondorHollowSkeletonIds.lessonsListMiddleScreen: const SkeletonResult(
      name: CondorHollowSkeletonIds.lessonsListMiddleScreen,
      width: 600,
      height: 400,
      bones: [
        Bone(
          x: -14,
          y: -4,
          w: 130,
          h: 40,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: -14,
          y: 44,
          w: 130,
          h: 40,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: -14,
          y: 92,
          w: 130,
          h: 40,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: -14,
          y: 140,
          w: 130,
          h: 40,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: -14,
          y: 188,
          w: 130,
          h: 40,
          borderRadius: BorderRadiusData.uniform(12),
        ),
      ],
    ),
    CondorHollowSkeletonIds.tasksList: const SkeletonResult(
      name: CondorHollowSkeletonIds.tasksList,
      width: 360,
      height: 304,
      bones: [
        Bone(
          x: 2,
          y: 2,
          w: 96,
          h: 300,
          borderRadius: BorderRadiusData.uniform(14),
          isContainer: true,
        ),
        Bone(
          x: 4,
          y: 8,
          w: 92,
          h: 64,
          borderRadius: BorderRadiusData.uniform(10),
        ),
        Bone(
          x: 4,
          y: 80,
          w: 92,
          h: 64,
          borderRadius: BorderRadiusData.uniform(10),
        ),
        Bone(
          x: 4,
          y: 152,
          w: 92,
          h: 64,
          borderRadius: BorderRadiusData.uniform(10),
        ),
        Bone(
          x: 4,
          y: 224,
          w: 92,
          h: 64,
          borderRadius: BorderRadiusData.uniform(10),
        ),
      ],
    ),
    CondorHollowSkeletonIds.courseScreenInitial: const SkeletonResult(
      name: CondorHollowSkeletonIds.courseScreenInitial,
      width: 900,
      height: 560,
      bones: [
        Bone(
          x: 0,
          y: 0,
          w: 100,
          h: 560,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 2,
          y: 12,
          w: 28,
          h: 520,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: 34,
          y: 16,
          w: 62,
          h: 22,
          borderRadius: BorderRadiusData.uniform(8),
        ),
        Bone(
          x: 34,
          y: 48,
          w: 62,
          h: 220,
          borderRadius: BorderRadiusData.uniform(14),
        ),
        Bone(
          x: 34,
          y: 280,
          w: 52,
          h: 14,
          borderRadius: BorderRadiusData.uniform(6),
        ),
        Bone(
          x: 34,
          y: 302,
          w: 40,
          h: 14,
          borderRadius: BorderRadiusData.uniform(6),
        ),
        Bone(
          x: 34,
          y: 324,
          w: 46,
          h: 14,
          borderRadius: BorderRadiusData.uniform(6),
        ),
      ],
    ),
    CondorHollowSkeletonIds.lessonTasksDetailPanelFullScreen:
        const SkeletonResult(
          name: CondorHollowSkeletonIds.lessonTasksDetailPanelFullScreen,
          width: 600,
          height: 420,
          bones: [
            Bone(
              x: 1.4,
              y: 16,
              w: 20,
              h: 24,
              borderRadius: BorderRadiusData.uniform(6),
            ),

            Bone(
              x: 87,
              y: 16,
              w: 12,
              h: 18,
              borderRadius: BorderRadiusData.uniform(6),
            ),

            Bone(
              x: 1.8,
              y: 68,
              w: 96.5,
              h: 466,
              borderRadius: BorderRadiusData.uniform(12),
            ),
          ],
        ),
    CondorHollowSkeletonIds.lessonAnswersDetailPanelFullScreen:
        const SkeletonResult(
          name: CondorHollowSkeletonIds.lessonAnswersDetailPanelFullScreen,
          width: 600,
          height: 420,
          bones: [
            Bone(
              x: 1.4,
              y: 16,
              w: 20,
              h: 24,
              borderRadius: BorderRadiusData.uniform(6),
            ),
            Bone(
              x: 1.8,
              y: 68,
              w: 96.5,
              h: 466,
              borderRadius: BorderRadiusData.uniform(12),
            ),
          ],
        ),
    CondorHollowSkeletonIds.lessonDetailPanelMiddleScreen: const SkeletonResult(
      name: CondorHollowSkeletonIds.lessonDetailPanelMiddleScreen,
      width: 600,
      height: 420,
      bones: [
        Bone(
          x: 3.2,
          y: 16,
          w: 30,
          h: 24,
          borderRadius: BorderRadiusData.uniform(6),
        ),

        Bone(
          x: 79,
          y: 16,
          w: 18,
          h: 18,
          borderRadius: BorderRadiusData.uniform(6),
        ),

        Bone(
          x: 1.8,
          y: 68,
          w: 96.5,
          h: 280,
          borderRadius: BorderRadiusData.uniform(12),
        ),
        Bone(
          x: 4,
          y: 370,
          w: 28,
          h: 20,
          borderRadius: BorderRadiusData.uniform(4),
        ),
      ],
    ),
    CondorHollowSkeletonIds.knowledgeBaseNews: const SkeletonResult(
      name: CondorHollowSkeletonIds.knowledgeBaseNews,
      width: 360,
      height: 132,
      bones: [
        Bone(
          x: 2,
          y: 4,
          w: 96,
          h: 124,
          borderRadius: BorderRadiusData.uniform(12),
          isContainer: true,
        ),
        Bone(
          x: 6,
          y: 12,
          w: 88,
          h: 14,
          borderRadius: BorderRadiusData.uniform(6),
        ),
        Bone(
          x: 6,
          y: 34,
          w: 88,
          h: 14,
          borderRadius: BorderRadiusData.uniform(6),
        ),
        Bone(
          x: 6,
          y: 56,
          w: 72,
          h: 14,
          borderRadius: BorderRadiusData.uniform(6),
        ),
        Bone(
          x: 6,
          y: 78,
          w: 88,
          h: 14,
          borderRadius: BorderRadiusData.uniform(6),
        ),
      ],
    ),
    CondorHollowSkeletonIds.roadmapMainFullScreen: const SkeletonResult(
      name: CondorHollowSkeletonIds.roadmapMainFullScreen,
      width: 1200,
      height: 600,
      bones: [
        Bone(
          x: 0,
          y: 0,
          w: 64,
          h: 540,
          borderRadius: BorderRadiusData.uniform(24),
          isContainer: true,
        ),

        Bone(
          x: 65,
          y: 0,
          w: 35,
          h: 540,
          borderRadius: BorderRadiusData.uniform(24),
          isContainer: true,
        ),
        Bone(
          x: 66,
          y: 18,
          w: 20,
          h: 24,
          borderRadius: BorderRadiusData.uniform(6),
        ),
        Bone(
          x: 66,
          y: 80,
          w: 30,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),
        Bone(
          x: 66,
          y: 105,
          w: 24,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),
        Bone(
          x: 66,
          y: 130,
          w: 15,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),
      ],
    ),
    CondorHollowSkeletonIds.roadmapMainMiddleScreen: const SkeletonResult(
      name: CondorHollowSkeletonIds.roadmapMainMiddleScreen,
      width: 600,
      height: 1000,
      bones: [
        Bone(
          x: 0,
          y: 0,
          w: 100,
          h: 316,
          borderRadius: BorderRadiusData.uniform(24),
          isContainer: true,
        ),

        Bone(
          x: 0,
          y: 330,
          w: 100,
          h: 200,
          borderRadius: BorderRadiusData.uniform(24),
          isContainer: true,
        ),

        Bone(
          x: 2,
          y: 350,
          w: 20,
          h: 24,
          borderRadius: BorderRadiusData.uniform(6),
        ),
        Bone(
          x: 2,
          y: 410,
          w: 40,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),
        Bone(
          x: 2,
          y: 430,
          w: 30,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),
        Bone(
          x: 2,
          y: 450,
          w: 15,
          h: 12,
          borderRadius: BorderRadiusData.uniform(4),
        ),
      ],
    ),
    CondorHollowSkeletonIds.youtubeThumb: const SkeletonResult(
      name: CondorHollowSkeletonIds.youtubeThumb,
      width: 400,
      height: 220,
      bones: [
        Bone(
          x: 1,
          y: 1,
          w: 98,
          h: 218,
          borderRadius: BorderRadiusData.uniform(12),
          isContainer: true,
        ),
        Bone(
          x: 3,
          y: 3,
          w: 94,
          h: 212,
          borderRadius: BorderRadiusData.uniform(10),
        ),
      ],
    ),
    CondorHollowSkeletonIds.lessonScreen: const SkeletonResult(
      name: CondorHollowSkeletonIds.lessonScreen,
      width: 400,
      height: 520,
      bones: [
        Bone(
          x: 6,
          y: 6,
          w: 88,
          h: 508,
          borderRadius: BorderRadiusData.uniform(18),
          isContainer: true,
        ),
        Bone(
          x: 14,
          y: 120,
          w: 72,
          h: 200,
          borderRadius: BorderRadiusData.uniform(14),
        ),
        Bone(
          x: 22,
          y: 340,
          w: 56,
          h: 12,
          borderRadius: BorderRadiusData.uniform(6),
        ),
        Bone(
          x: 22,
          y: 362,
          w: 40,
          h: 12,
          borderRadius: BorderRadiusData.uniform(6),
        ),
      ],
    ),
    CondorHollowSkeletonIds.customLoader: const SkeletonResult(
      name: CondorHollowSkeletonIds.customLoader,
      width: 280,
      height: 300,
      bones: [
        Bone(
          x: 8,
          y: 0,
          w: 84,
          h: 200,
          borderRadius: BorderRadiusData.uniform(16),
          isContainer: true,
        ),
        Bone(
          x: 28,
          y: 220,
          w: 44,
          h: 10,
          borderRadius: BorderRadiusData.uniform(5),
        ),
        Bone(
          x: 34,
          y: 240,
          w: 32,
          h: 10,
          borderRadius: BorderRadiusData.uniform(5),
        ),
      ],
    ),
    CondorHollowSkeletonIds.authSubmitButton: const SkeletonResult(
      name: CondorHollowSkeletonIds.authSubmitButton,
      width: 120,
      height: 22,
      bones: [
        Bone(
          x: 4,
          y: 2,
          w: 92,
          h: 18,
          borderRadius: BorderRadiusData.uniform(6),
        ),
      ],
    ),
  });
}
